use crate::models::AICommitAnalysis;
use crate::traits::git_provider::GitProvider;
use anyhow::Result;
use std::path::Path;

pub async fn analyze_ai_commits(git: &impl GitProvider, path: &Path) -> Result<AICommitAnalysis> {
    let history = git.get_history(path).await?;
    let total_commits = history.len();
    let mut ai_generated_count = 0;
    let mut confidence_scores = vec![];
    let mut patterns_detected = vec![];

    let author_patterns = ["claude", "copilot", "chatgpt", "codium", "genie"];
    let message_patterns = [
        "co-authored-by",
        "generated with",
        "generated by",
        "assisted by",
    ];

    for commit in history {
        let mut confidence = 0;
        let mut detected_in_commit = vec![];

        for pattern in &author_patterns {
            if commit.author.to_lowercase().contains(pattern) {
                confidence += 50;
                detected_in_commit.push(format!("Author pattern: {}", pattern));
            }
        }

        for pattern in &message_patterns {
            if commit.message.to_lowercase().contains(pattern) {
                confidence += 50;
                detected_in_commit.push(format!("Message pattern: {}", pattern));
            }
        }

        if confidence > 0 {
            ai_generated_count += 1;
            let final_confidence = std::cmp::min(100, confidence);
            confidence_scores.push((commit.sha.clone(), final_confidence));
            patterns_detected.extend(detected_in_commit);
        }
    }

    Ok(AICommitAnalysis {
        total_commits,
        ai_generated_count,
        confidence_scores,
        patterns_detected,
    })
}

#[allow(clippy::unwrap_used, clippy::expect_used)]
#[cfg(test)]
mod tests {
    use super::*;
    use crate::mocks::MockGit;
    use crate::traits::git_provider::Commit;
    use std::path::PathBuf;

    // NOTE: Test code uses unwrap() for test fixtures and assertions.
    // This is acceptable because:
    // 1. Test data is controlled and known to be valid
    // 2. Test failures (panics) are the desired outcome when setup fails
    // 3. Panics in tests provide clear failure points for debugging

    #[tokio::test]
    async fn test_analyze_ai_commits_no_ai() {
        let commits = vec![
            Commit {
                sha: "1".to_string(),
                author: "human1".to_string(),
                timestamp: 0,
                message: "feat: initial commit".to_string(),
            },
            Commit {
                sha: "2".to_string(),
                author: "human2".to_string(),
                timestamp: 0,
                message: "fix: a bug".to_string(),
            },
        ];
        let git = MockGit::new().with_commits(commits);
        let result = analyze_ai_commits(&git, &PathBuf::from(".")).await.unwrap();

        assert_eq!(result.total_commits, 2);
        assert_eq!(result.ai_generated_count, 0);
        assert!(result.confidence_scores.is_empty());
        assert!(result.patterns_detected.is_empty());
    }

    #[tokio::test]
    async fn test_analyze_ai_commits_with_ai() {
        let commits = vec![
            Commit {
                sha: "1".to_string(),
                author: "human1".to_string(),
                timestamp: 0,
                message: "feat: initial commit".to_string(),
            },
            Commit {
                sha: "2".to_string(),
                author: "copilot".to_string(),
                timestamp: 0,
                message: "feat: add new feature".to_string(),
            },
            Commit {
                sha: "3".to_string(),
                author: "human2".to_string(),
                timestamp: 0,
                message: "fix: a bug. Generated with ChatGPT".to_string(),
            },
        ];
        let git = MockGit::new().with_commits(commits);
        let result = analyze_ai_commits(&git, &PathBuf::from(".")).await.unwrap();

        assert_eq!(result.total_commits, 3);
        assert_eq!(result.ai_generated_count, 2);
        assert_eq!(result.confidence_scores.len(), 2);
        assert_eq!(result.confidence_scores[0], ("2".to_string(), 50));
        assert_eq!(result.confidence_scores[1], ("3".to_string(), 50));
        assert_eq!(result.patterns_detected.len(), 2);
    }
}
