/**
 * Auto-generated TypeScript bindings from Rust code-viz-tauri crate
 *
 * This file contains types that correspond to the Rust structs and commands
 * exposed via Tauri IPC. These types are kept in sync with the Rust definitions.
 *
 * @generated by tauri-specta
 */

/**
 * Hierarchical node representing a file or directory in the codebase tree
 *
 * Corresponds to Rust struct: code_viz_tauri::models::TreeNode
 */
export interface TreeNode {
  /** Unique identifier for this node (typically the full path) */
  id: string;

  /** Display name (file/directory name without full path) */
  name: string;

  /** Full path from repository root */
  path: string;

  /** Lines of code (for files) or sum of children (for directories) */
  loc: number;

  /**
   * Complexity score (0-100 scale, calculated as loc/10 for MVP)
   * This is a placeholder metric; future versions may use cyclomatic complexity
   */
  complexity: number;

  /** Node type: "file" or "directory" */
  type: "file" | "directory";

  /** Child nodes (empty for files, contains children for directories) */
  children: TreeNode[];

  /** Last modified timestamp (ISO 8601 format) */
  lastModified: string;

  /** Dead code ratio (0.0 to 1.0), only present when dead code analysis is enabled */
  deadCodeRatio?: number;
}

/**
 * Type of symbol in source code
 *
 * Corresponds to Rust enum: code_viz_dead_code::models::SymbolKind
 */
export type SymbolKind =
  | "Function"
  | "ArrowFunction"
  | "Class"
  | "Method"
  | "Variable";

/**
 * A dead (unreachable) symbol with metadata
 *
 * Corresponds to Rust struct: code_viz_dead_code::models::DeadSymbol
 */
export interface DeadSymbol {
  /** Symbol name */
  symbol: string;

  /** Type of symbol */
  kind: SymbolKind;

  /** Starting line number */
  lineStart: number;

  /** Ending line number */
  lineEnd: number;

  /** Lines of code in this symbol */
  loc: number;

  /** Deletion confidence score (0-100) */
  confidence: number;

  /** Reason why this symbol is marked as dead */
  reason: string;

  /** Last modification time (ISO 8601 format, if available) */
  lastModified?: string;
}

/**
 * Dead code found in a single file
 *
 * Corresponds to Rust struct: code_viz_dead_code::models::FileDeadCode
 */
export interface FileDeadCode {
  /** File path */
  path: string;

  /** List of dead symbols in this file */
  deadCode: DeadSymbol[];
}

/**
 * Summary statistics for dead code analysis
 *
 * Corresponds to Rust struct: code_viz_dead_code::models::DeadCodeSummary
 */
export interface DeadCodeSummary {
  /** Total number of files analyzed */
  totalFiles: number;

  /** Number of files containing dead code */
  filesWithDeadCode: number;

  /** Total number of dead functions */
  deadFunctions: number;

  /** Total number of dead classes */
  deadClasses: number;

  /** Total lines of dead code */
  totalDeadLoc: number;

  /** Ratio of dead code to total code (0.0 to 1.0) */
  deadCodeRatio: number;
}

/**
 * Complete result of dead code analysis
 *
 * Corresponds to Rust struct: code_viz_dead_code::models::DeadCodeResult
 */
export interface DeadCodeResult {
  /** Aggregated summary statistics */
  summary: DeadCodeSummary;

  /** Dead code grouped by file */
  files: FileDeadCode[];
}

/**
 * Tauri Commands
 *
 * These functions wrap the Tauri invoke API for type-safe command invocation.
 */

/**
 * Analyzes a repository and returns hierarchical tree structure for visualization
 *
 * @param path - Absolute path to the repository root directory
 * @param requestId - Optional UUID for correlating frontend and backend logs
 * @returns Promise resolving to the root TreeNode
 * @throws Error if path does not exist, is not a directory, or analysis fails
 *
 * @example
 * ```typescript
 * import { analyzeRepository } from './types/bindings';
 *
 * const requestId = crypto.randomUUID();
 * const tree = await analyzeRepository('/home/user/my-project', requestId);
 * console.log(`Total LOC: ${tree.loc}`);
 * ```
 */
export async function analyzeRepository(
  path: string,
  requestId?: string
): Promise<TreeNode> {
  const { invoke } = await import('@tauri-apps/api/core');
  return invoke<TreeNode>('analyze_repository', {
    path,
    request_id: requestId
  });
}

/**
 * Analyzes dead code in a repository and returns filtered results
 *
 * @param path - Absolute path to the repository root directory
 * @param minConfidence - Minimum confidence score (0-100) for dead code inclusion
 * @param requestId - Optional UUID for correlating frontend and backend logs
 * @returns Promise resolving to dead code analysis results
 * @throws Error if path does not exist, is not a directory, or analysis fails
 *
 * @example
 * ```typescript
 * import { analyzeDeadCode } from './types/bindings';
 *
 * const requestId = crypto.randomUUID();
 * const result = await analyzeDeadCode('/home/user/my-project', 80, requestId);
 * console.log(`Found ${result.summary.deadFunctions} dead functions`);
 * ```
 */
export async function analyzeDeadCode(
  path: string,
  minConfidence: number,
  requestId?: string
): Promise<DeadCodeResult> {
  const { invoke } = await import('@tauri-apps/api/core');
  return invoke<DeadCodeResult>('analyze_dead_code_command', {
    path,
    min_confidence: minConfidence,
    request_id: requestId
  });
}
