/**
 * Auto-generated TypeScript bindings from Rust code-viz-tauri crate
 *
 * This file contains types that correspond to the Rust structs and commands
 * exposed via Tauri IPC. These types are kept in sync with the Rust definitions.
 *
 * @generated by tauri-specta
 */

/**
 * Hierarchical node representing a file or directory in the codebase tree
 *
 * Corresponds to Rust struct: code_viz_tauri::models::TreeNode
 */
export interface TreeNode {
  /** Unique identifier for this node (typically the full path) */
  id: string;

  /** Display name (file/directory name without full path) */
  name: string;

  /** Full path from repository root */
  path: string;

  /** Lines of code (for files) or sum of children (for directories) */
  loc: number;

  /**
   * Complexity score (0-100 scale, calculated as loc/10 for MVP)
   * This is a placeholder metric; future versions may use cyclomatic complexity
   */
  complexity: number;

  /** Node type: "file" or "directory" */
  type: "file" | "directory";

  /** Child nodes (empty for files, contains children for directories) */
  children: TreeNode[];

  /** Last modified timestamp (ISO 8601 format) */
  lastModified: string;
}

/**
 * Tauri Commands
 *
 * These functions wrap the Tauri invoke API for type-safe command invocation.
 */

/**
 * Analyzes a repository and returns hierarchical tree structure for visualization
 *
 * @param path - Absolute path to the repository root directory
 * @param requestId - Optional UUID for correlating frontend and backend logs
 * @returns Promise resolving to the root TreeNode
 * @throws Error if path does not exist, is not a directory, or analysis fails
 *
 * @example
 * ```typescript
 * import { analyzeRepository } from './types/bindings';
 *
 * const requestId = crypto.randomUUID();
 * const tree = await analyzeRepository('/home/user/my-project', requestId);
 * console.log(`Total LOC: ${tree.loc}`);
 * ```
 */
export async function analyzeRepository(
  path: string,
  requestId?: string
): Promise<TreeNode> {
  const { invoke } = await import('@tauri-apps/api/core');
  return invoke<TreeNode>('analyze_repository', {
    path,
    request_id: requestId
  });
}
