/**
 * Auto-generated TypeScript bindings from Rust code-viz-tauri crate
 *
 * This file contains types that correspond to the Rust structs and commands
 * exposed via Tauri IPC. These types are kept in sync with the Rust definitions.
 *
 * @generated by tauri-specta
 */

/**
 * Hierarchical node representing a file or directory in the codebase tree
 *
 * Corresponds to Rust struct: code_viz_tauri::models::TreeNode
 */
export interface CouplingMetrics {
  /** Number of incoming dependencies (other modules that depend on this one) */
  afferentCoupling: number;
  /** Number of outgoing dependencies (modules this one depends on) */
  efferentCoupling: number;
  /** Instability metric (Efferent / (Afferent + Efferent)), ranges from 0 (stable) to 1 (unstable) */
  instability: number;
}

export interface CodeChurn {
  addedLines: number;
  deletedLines: number;
}

export interface FunctionComplexity {
  name: string;
  complexity: number;
  startLine: number;
  endLine: number;
}

export interface CognitiveComplexity {
  /** Total cognitive complexity for the file */
  totalComplexity: number;
  /** Average complexity per function */
  averageComplexity: number;
  /** Maximum complexity among all functions */
  maxComplexity: number;
  /** Per-function complexity details */
  functions: FunctionComplexity[];
}

export interface TestCoverage {
  /** Line coverage percentage (0.0 - 100.0) */
  lineCoverage: number;
  /** Number of lines covered */
  linesCovered: number;
  /** Total number of executable lines */
  totalLines: number;
  /** Branch coverage percentage (0.0 - 100.0), if available */
  branchCoverage?: number;
}

export interface TreeNode {
  /** Unique identifier for this node (typically the full path) */
  id: string;

  /** Display name (file/directory name without full path) */
  name: string;

  /** Full path from repository root */
  path: string;

  /** Lines of code (for files) or sum of children (for directories) */
  loc: number;

  /**
   * Complexity score (0-100 scale, calculated as loc/10 for MVP)
   * This is a placeholder metric; future versions may use cyclomatic complexity
   */
  complexity: number;

  /** Node type: "file" or "directory" */
  type: "file" | "directory";

  /** Child nodes (empty for files, contains children for directories) */
  children: TreeNode[];

  /** Last modified timestamp (ISO 8601 format) */
  lastModified: string;

  /** Dead code ratio (0.0 to 1.0), only present when dead code analysis is enabled */
  deadCodeRatio?: number;

  // Additional metrics from FileMetrics (only present for files)

  /** Programming language ("rust", "typescript", "python", etc.) - only for files */
  language?: string;

  /** File size in bytes - only for files */
  sizeBytes?: number;

  /** Number of functions/methods - only for files */
  functionCount?: number;

  /** Coupling metrics (afferent, efferent, instability) */
  coupling?: CouplingMetrics;

  /** Code churn metrics (lines added/deleted from git) */
  codeChurn?: CodeChurn;

  /** AI Bloat Index: (comment_lines / code_lines) * 100 */
  aiBloatIndex?: number;

  /** Cognitive complexity metrics (SonarSource algorithm) */
  cognitiveComplexity?: CognitiveComplexity;

  /** Test coverage metrics (from llvm-cov, tarpaulin, etc.) */
  testCoverage?: TestCoverage;
}

/**
 * Type of symbol in source code
 *
 * Corresponds to Rust enum: code_viz_dead_code::models::SymbolKind
 */
export type SymbolKind =
  | "Function"
  | "ArrowFunction"
  | "Class"
  | "Method"
  | "Variable";

/**
 * A dead (unreachable) symbol with metadata
 *
 * Corresponds to Rust struct: code_viz_dead_code::models::DeadSymbol
 */
export interface DeadSymbol {
  /** Symbol name */
  symbol: string;

  /** Type of symbol */
  kind: SymbolKind;

  /** Starting line number */
  lineStart: number;

  /** Ending line number */
  lineEnd: number;

  /** Lines of code in this symbol */
  loc: number;

  /** Deletion confidence score (0-100) */
  confidence: number;

  /** Reason why this symbol is marked as dead */
  reason: string;

  /** Last modification time (ISO 8601 format, if available) */
  lastModified?: string;
}

/**
 * Dead code found in a single file
 *
 * Corresponds to Rust struct: code_viz_dead_code::models::FileDeadCode
 */
export interface FileDeadCode {
  /** File path */
  path: string;

  /** List of dead symbols in this file */
  deadCode: DeadSymbol[];
}

/**
 * Summary statistics for dead code analysis
 *
 * Corresponds to Rust struct: code_viz_dead_code::models::DeadCodeSummary
 */
export interface DeadCodeSummary {
  /** Total number of files analyzed */
  totalFiles: number;

  /** Number of files containing dead code */
  filesWithDeadCode: number;

  /** Total number of dead functions */
  deadFunctions: number;

  /** Total number of dead classes */
  deadClasses: number;

  /** Total lines of dead code */
  totalDeadLoc: number;

  /** Ratio of dead code to total code (0.0 to 1.0) */
  deadCodeRatio: number;
}

/**
 * Complete result of dead code analysis
 *
 * Corresponds to Rust struct: code_viz_dead_code::models::DeadCodeResult
 */
export interface DeadCodeResult {
  /** Aggregated summary statistics */
  summary: DeadCodeSummary;

  /** Dead code grouped by file */
  files: FileDeadCode[];
}

/**
 * Analysis options - configure which features to enable
 *
 * Corresponds to Rust struct: code_viz_tauri::models::AnalysisOptions
 */
export interface AnalysisOptions {
  /** Enable code duplication detection */
  enableDuplicates?: boolean;

  /** Minimum lines for duplicate detection (default: 5) */
  minDuplicateLines?: number;

  /** Enable git hotspot detection */
  enableHotspots?: boolean;

  /** Maximum number of hotspots to report (default: 10) */
  maxHotspots?: number;

  /** Enable AI commit analysis */
  enableAiCommits?: boolean;

  /** Path to test coverage report (llvm-cov or Tarpaulin JSON) */
  coverageReportPath?: string;
}

/**
 * Tauri Commands
 *
 * These functions wrap the Tauri invoke API for type-safe command invocation.
 */

/**
 * Analyzes a repository and returns hierarchical tree structure for visualization
 *
 * @param path - Absolute path to the repository root directory
 * @param options - Analysis options to configure which features to enable
 * @param requestId - Optional UUID for correlating frontend and backend logs
 * @returns Promise resolving to the root TreeNode
 * @throws Error if path does not exist, is not a directory, or analysis fails
 *
 * @example
 * ```typescript
 * import { analyzeRepository } from './types/bindings';
 *
 * const requestId = crypto.randomUUID();
 * const tree = await analyzeRepository('/home/user/my-project', {
 *   enableDuplicates: true,
 *   enableHotspots: true,
 *   minDuplicateLines: 5,
 *   maxHotspots: 10
 * }, requestId);
 * console.log(`Total LOC: ${tree.loc}`);
 * ```
 */
export async function analyzeRepository(
  path: string,
  options: AnalysisOptions,
  requestId?: string
): Promise<TreeNode> {
  const { invoke } = await import('@tauri-apps/api/core');
  return invoke<TreeNode>('analyze_repository', {
    path,
    options,
    request_id: requestId
  });
}

/**
 * Analyzes dead code in a repository and returns filtered results
 *
 * @param path - Absolute path to the repository root directory
 * @param minConfidence - Minimum confidence score (0-100) for dead code inclusion
 * @param requestId - Optional UUID for correlating frontend and backend logs
 * @returns Promise resolving to dead code analysis results
 * @throws Error if path does not exist, is not a directory, or analysis fails
 *
 * @example
 * ```typescript
 * import { analyzeDeadCode } from './types/bindings';
 *
 * const requestId = crypto.randomUUID();
 * const result = await analyzeDeadCode('/home/user/my-project', 80, requestId);
 * console.log(`Found ${result.summary.deadFunctions} dead functions`);
 * ```
 */
export async function analyzeDeadCode(
  path: string,
  minConfidence: number,
  requestId?: string
): Promise<DeadCodeResult> {
  const { invoke } = await import('@tauri-apps/api/core');
  return invoke<DeadCodeResult>('analyze_dead_code_command', {
    path,
    min_confidence: minConfidence,
    request_id: requestId
  });
}
